Rename Person class to Sender for transactions models
LBHackney-IT/housing-search-shared pull request #16
Opened 2021-11-27 14:26 UTC by AnnaGolosova

2021-11-28 18:00 UTC, HHjolany requested changes

2021-11-28 18:00 UTC, HHjolany commented on Hackney.Shared.HousingSearch/Gateways/Models/Transactions/QueryableTransaction.cs
> +                BalanceAmount, HousingBenefitAmount, Address, Sender.ToSender(), Fund);
Is possible to have Null Sender?
Sender?.ToPerson()

2021-11-28 18:00 UTC, HHjolany commented on Hackney.Shared.HousingSearch/Gateways/Models/Transactions/QueryableTransaction.cs
>                  BankAccountNumber, IsSuspense, SuspenseResolutionInfo.ToSuspenseResolutionInfo(), PaidAmount, ChargedAmount,
Is possible to have Null SuspenseResolutionInfo?
SuspenseResolutionInfo?.ToSuspenseResolutionInfo()

2021-11-29 07:55 UTC, AnnaGolosova commented on Hackney.Shared.HousingSearch/Gateways/Models/Transactions/QueryableTransaction.cs
> +                BalanceAmount, HousingBenefitAmount, Address, Sender.ToSender(), Fund);
Ok, thanks! I will fix it

2021-11-29 09:26 UTC, HHjolany approved these changes

2021-11-29 10:42 UTC, LBHMGeorgieva approved these changes

2021-11-29 14:35 UTC, merged